# Generated by Django 4.1.5 on 2023-08-27 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('audio', models.FileField(upload_to='uploads/')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('extension', models.CharField(max_length=10)),
                ('size', models.CharField(max_length=20)),
            ],
        ),
    ]
